// <auto-generated />
namespace AucApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_ImgUrl_property_to_products : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_ImgUrl_property_to_products));
        
        string IMigrationMetadata.Id
        {
            get { return "201703101108239_add_ImgUrl_property_to_products"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
